# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-warn-script-location numpy scipy matplotlib==3.1.0 msvc-runtime h5py pypiwin32 pyinstaller requests
        pyinstaller VSANS_ReductionHighRes.py
        pyinstaller -F get_ncnr_files.py

    - name: Run a script
      run: |
        Compress-Archive -Path dist\VSANS_ReductionHighRes -DestinationPath dist.zip
      shell: powershell
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: test.exe
        path: dist\get_ncnr_files.exe
    - name: Update release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: prerelease
        tag: alpha
        files: dist.zip dist\get_ncnr_files.exe
     
  macos-build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-warn-script-location numpy scipy matplotlib==3.1.0 h5py pyinstaller requests
        pyinstaller VSANS_ReductionHighRes.py
        pyinstaller -F get_ncnr_files.py --windowed

    - name: Run a script
      run: zip dist_osx.zip dist/VSANS_ReductionHighRes/*
      shell: bash

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: test.app
        path: dist/get_ncnr_files.app
    - name: Update release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: prerelease
        tag: alpha
        files: dist_osx.zip dist/get_ncnr_files.app